name: Deploy Tiddlywiki To Github Pages

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
<<<<<<< HEAD
<<<<<<< HEAD
      - uses: actions/checkout@v2
=======
      - uses: actions/checkout@v3
>>>>>>> 3a47f8b (Commit with Git-Sync-JS)
=======
      - uses: actions/checkout@v3
>>>>>>> f55773e (Commit with Git-Sync-JS)
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '16'

      - name: Cache dependencies
<<<<<<< HEAD
<<<<<<< HEAD
        uses: actions/cache@v2
=======
        uses: actions/cache@v3
>>>>>>> 3a47f8b (Commit with Git-Sync-JS)
=======
        uses: actions/cache@v3
>>>>>>> f55773e (Commit with Git-Sync-JS)
        with:
          path: |
            **/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/package.json') }}
      - name: Install Dependency
        run: npm install
      - name: Build
        run: npm run build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public-dist
